persistence/jpa-2-entities-lock/src/main/java/ex/entity/Human.java
package ex.entity;

import javax.persistence.*;

@Entity
public class Human {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    public String name;

    /**
     * If you remove @Version, there will be no optimistic checking, any dirty-updates will not be detected
     */
    @Version
    public Integer version;

    public Human() {
    }

    public Human(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}

persistence/jpa-2-entities-lock/src/main/java/ex/web/Bean.java
package ex.web;

import ex.ejb.EjbMain;
import ex.entity.Human;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named("bean")
@RequestScoped
public class Bean {
    @EJB
    EjbMain ejb;

    Human oneHuman;

    @PostConstruct
    public void init() {
        oneHuman = ejb.getHuman(1L);
    }

    public Human getOneHuman() {
        return oneHuman;
    }

    public void doVoidPessimisticLock() {
        ejb.voidPessimisticLock();
    }

    /**
     * Does a dirty-update before merging it
     */
    public void doUpdateDirty() {
        ejb.dirtyUpdate(oneHuman);
    }

    public void doUpdateNameOne() {
        oneHuman = ejb.update(oneHuman, "Name One");
    }

    public void doUpdateNameTwo() {
        oneHuman = ejb.update(oneHuman, "Name Two");
    }
}

persistence/jpa-2-entities-lock/src/main/java/ex/web/SessionBean.java
package ex.web;

import ex.ejb.EjbStateful;
import ex.entity.Human;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.persistence.LockModeType;
import java.io.Serializable;
import java.util.Random;

@Named
@SessionScoped
public class SessionBean implements Serializable {
    @EJB
    EjbStateful ejb;

    Integer random;
    Human subject;
    Human untouched;

    @PostConstruct
    public void init() {
        subject = ejb.getHuman(1L, LockModeType.OPTIMISTIC);
        untouched = ejb.getHuman(2L, LockModeType.OPTIMISTIC);
        Random r = new Random();
        random = r.nextInt(1000);
    }

    /**
     * This is so that the page is refreshed, immediately showing new random values
     * <p>
     * Without a refresh, the page still shows old data even though it is gone
     */
    public String destroy() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return FacesContext.getCurrentInstance().getViewRoot().getViewId() + "?faces-redirect=true";
    }

    public void ninjaEdit(int i) {
        ejb.ninjaEdit(i);
    }

    public void normalEdit() {
        ejb.normalEdit(subject);
    }

    public Integer getRandom() {
        return random;
    }

    /**
     * The entity is guaranteed to be managed as long the Persistence Context is extended
     */
    public boolean isHumanManaged() {
        return ejb.isManaged(subject);
    }

    public Human getSubject() {
        return subject;
    }
}

persistence/jpa-2-entities-lock/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
<f:view>
    <div>
        <p>This page shows the effect of locks and version column on unmanaged entities</p>
        <h:form>
            <h:commandButton value="Pessimistic Lock" action="#{bean.doVoidPessimisticLock}"/>
            <h:commandButton value="Dirty Update (will rollback)" action="#{bean.doUpdateDirty}"/>
            <h:commandButton value="Normal Update (Name One)" action="#{bean.doUpdateNameOne}"/>
            <h:commandButton value="Normal Update (Name Two)" action="#{bean.doUpdateNameTwo}"/>
        </h:form>
        <hr/>
        <h:link outcome="stateful" value="Test Stateful with Lock"/>
    </div>
    <div>
        <p>#{bean.oneHuman.id}: #{bean.oneHuman.name} (#{bean.oneHuman.version})</p>
    </div>
    <div>
        <h2>Notes</h2>
        <ol>
            <li>Pessimistic Lock button shows SQL generation of database low rock</li>
            <li>Clicking on the dirty update button does a rollback. It first makes a dirty-update, then merges a different value. No change is done as the dirty-update is part of the rollback-ed transaction</li>
            <li>Normal Update just shows how each update increments the version column. Making no changes does not increment version column</li>
        </ol>
    </div>
</f:view>
</html>

persistence/jpa-2-entities-lock/src/main/webapp/stateful.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <div>
        <h:form>
            <p>All Ninja Edits bypass Persistence Context</p>
            <h:commandButton value="Invalidate Current Session" action="#{sessionBean.destroy}"/><br/>
            <h:commandButton value="Ninja Edit" action="#{sessionBean.ninjaEdit(1)}"/><br/>
            <h:commandButton value="Ninja Edit Hidden Data" action="#{sessionBean.ninjaEdit(2)}"/><br/>
            <h:commandButton value="Ninja Edit Unrelated Data" action="#{sessionBean.ninjaEdit(3)}"/><br/>
            <h:commandButton value="Normal Edit" action="#{sessionBean.normalEdit}"/>
        </h:form>
        <h1>Session ID: #{sessionBean.random}</h1>
        <p>#{sessionBean.subject.id}: #{sessionBean.subject.name} (#{sessionBean.subject.version})</p>
        <p>Managed: #{sessionBean.humanManaged}</p>
    </div>
    <div>
        <h2>Notes</h2>
        <ol>
            <li>All entities here are managed by an Extended Persistence Context, thus the lifetime of managed entities last as long as this CDI session</li>
            <li>The first two ninja edit throws an OptimisticLockException, as the entities are still managed by the Stateful EJB, in which the EJB's lifetime is tied to the CDI SessionScope</li>
            <li>Also note that, Ninja Edit do not show its result immediately, as it bypasses the Persistence Context</li>
            <li>To save the trouble of creating another example without Lock, no errors happen, but Ninja Edit does not update currently managed entities, and that is a
                <b>big</b> problem
            </li>
        </ol>
    </div>
</f:view>
</html>