persistence/jpa-3-entitymanager-jpql/src/main/java/ex/web/Bean.java
package ex.web;

import ex.ejb.EjbEm;
import ex.ejb.EjbJpql;
import ex.entity2.AnalyticsSalary;
import ex.entity2.Company;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import java.util.List;

@Named("bean")
@RequestScoped
public class Bean {
    @EJB
    EjbEm em;

    @EJB
    EjbJpql jpql;

    AnalyticsSalary apple;
    AnalyticsSalary microsoft;

    @PostConstruct
    public void init() {
        apple = jpql.getAverageSalary("Apple");
        microsoft = jpql.getAverageSalary("Microsoft");
    }

    /*
    Try each one to see the effects of SQL production
     */
    public List<Company> getCompanies() {
        return jpql.getAllCompaniesJoinFetch();
//        return jpql.getAllCompanies();
//        return jpql.getAllCompanies(true);
//        return jpql.getAllCompanies(false);
    }

    public AnalyticsSalary getApple() {
        return apple;
    }

    public AnalyticsSalary getMicrosoft() {
        return microsoft;
    }

    public void update() {
//        jpql.updateAgeApple(); // n+1 select issue
        em.updateApple(); // no n+1 issue
    }

    public void delete() {
        jpql.deleteApple();
    }

}

persistence/jpa-3-entitymanager-jpql/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <h:form>
        <h:commandButton value="Update" action="#{bean.update}"/>
        <h:commandButton value="Delete" action="#{bean.delete}"/>
    </h:form>
    <div>
        <ui:repeat value="#{bean.companies}" var="c">
            <p>#{c.name}</p>
            <ol>
                <!-- in JSF 2.3, ui:repeat works with Set (Iterable) -->
                <ui:repeat value="#{c.workers.toArray()}" var="w">
                    <li>#{w.name}; Age: #{w.age}</li>
                </ui:repeat>
            </ol>
        </ui:repeat>
    </div>
    <div>
        <h1>Average Age</h1>
        <p>#{bean.apple.name} has an average age of #{bean.apple.integer}</p>
        <p>#{bean.microsoft.name} has an average age of #{bean.microsoft.integer}</p>
    </div>
</f:view>
</html>